/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    '备份': typeof import('./src/components/MyInput 备份.vue')['default']
    BottomCom: typeof import('./src/components/bottom-com.vue')['default']
    CenterCom: typeof import('./src/components/center-com.vue')['default']
    ChangeTheme: typeof import('./src/components/changeTheme.vue')['default']
    ComputeDemo: typeof import('./src/components/ComputeDemo.vue')['default']
    copy: typeof import('./src/components/watchDemo04 copy.vue')['default']
    FlexDemo: typeof import('./src/components/FlexDemo.vue')['default']
    GradientDemo: typeof import('./src/components/GradientDemo.vue')['default']
    GridAspectRatio: typeof import('./src/components/GridAspectRatio.vue')['default']
    GridAspectRatioSupports: typeof import('./src/components/GridAspectRatioSupports.vue')['default']
    GridDemo: typeof import('./src/components/GridDemo.vue')['default']
    GridDemoPro: typeof import('./src/components/GridDemoPro.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MyInput: typeof import('./src/components/MyInput.vue')['default']
    'MyInput 备份': typeof import('./src/components/MyInput 备份.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NFlex: typeof import('naive-ui')['NFlex']
    NSpace: typeof import('naive-ui')['NSpace']
    TestRef: typeof import('./src/components/TestRef.vue')['default']
    TsDemo: typeof import('./src/components/tsDemo.vue')['default']
    WatchDemo01: typeof import('./src/components/watchDemo01.vue')['default']
    WatchDemo02: typeof import('./src/components/watchDemo02.vue')['default']
    WatchDemo03: typeof import('./src/components/watchDemo03.vue')['default']
    WatchDemo04: typeof import('./src/components/watchDemo04.vue')['default']
    WatchDemo05: typeof import('./src/components/watchDemo05.vue')['default']
    WatchEffectddemo: typeof import('./src/components/watchEffectddemo.vue')['default']
    WatchEffectDemo: typeof import('./src/components/watchEffectDemo.vue')['default']
  }
}
